name: Build & Deploy - Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Select the semantic versioning bump.
        required: true
        options:
          - minor
          - patch
          - major

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/build

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-check:
    if: ${{ !contains(github.event.head_commit.message, '[bot] Update image tag to') || contains(github.event.pull_request.labels.*.name, 'skip build') == true}}
    runs-on: ubuntu-latest
    steps:
      - name: Check if build should continue
        run: |
          echo "Push to main is not from bot -> continue build"

  build-and-push:
    needs: build-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout Branch
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.8

      - name: Get bump
        run: |
          if [[ "${{ contains(steps.pr-labels.outputs.labels, 'major') }}" == "true" ]]; then
            echo "BUMP=major" >> $GITHUB_ENV
          elif [[ "${{ contains(steps.pr-labels.outputs.labels, 'minor') }}" == "true" ]]; then
            echo "BUMP=minor" >> $GITHUB_ENV
          elif [[ "${{ contains(steps.pr-labels.outputs.labels, 'patch') }}" == "true" ]]; then
            echo "BUMP=patch" >> $GITHUB_ENV
          else
            echo "BUMP=${{ inputs.bump }}" >> $GITHUB_ENV
          fi

      - name: Debug
        run: echo "${{ env.BUMP }}"

      - name: Bump & tag version
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          default_bump: ${{ github.event.inputs.bump }}
          fetch_all_tags: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: ${{ steps.tag.outputs.version }}
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.tag.outputs.version }}

      - name: Set environment variables
        if: ${{ steps.tag.outputs.version }}
        run: |
          echo "TAGS=${{ steps.meta.outputs.tags }}" >> $GITHUB_ENV
          echo "LABELS=${{ steps.meta.outputs.labels }}" >> $GITHUB_ENV
          echo "NEW_VERSION=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV

      - name: Build and push Docker image to ghcr.io
        if: ${{ steps.tag.outputs.version }}
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: ./nginx
          push: true
          tags: ${{ env.TAGS }}
          labels: ${{ env.LABELS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create GitHub release
        id: create_release
        if: ${{ steps.tag.outputs.version }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: ${{ env.NEW_VERSION }}
          draft: false
          prerelease: false

      - name: Update image tag in stack_definition.yaml
        if: ${{ steps.tag.outputs.version }}
        uses: mikefarah/yq@v4.43.1
        with:
          cmd: |
            yq -i '.stackDef.resources.applications."bulk-shipment-service".image.tag = "${{ env.NEW_VERSION }}"' stack-definition.yaml
            cat stack-definition.yaml

      - name: Update stack-definition.yaml
        id: commit
        if: ${{ steps.tag.outputs.version }}
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
        with:
          skip_fetch: false
          commit_message: |
            [bot] Update image tag to ${{ steps.tag.outputs.version }}

      - name: Print container version
        if: ${{ steps.tag.outputs.version }}
        run: |
          echo "New container version: ${{ env.NEW_VERSION }}"
          echo ':package: New container version: `${{ env.NEW_VERSION }}`' >> $GITHUB_STEP_SUMMARY

#  deploy-dev:
#    name: Deploy stack to development
#    needs: build-and-push
#    uses: ./.github/workflows/deployment-dev.yaml
#
#  deploy-prod:
#    name: Deploy stack to development
#    needs: deploy-dev
#    uses: ./.github/workflows/deployment-dev.yaml
#    with:
#      bundle_ref: ${{ needs.deploy-dev.outputs.bundle_ref }}
