name: Build NGINX - Prod

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Select the semantic versioning bump.
        required: true
        options:
          - minor
          - patch
          - major

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/nginx-redirect

jobs:
  skip-if-illegal-branch:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Illegal Branch Check Outcome
        run: echo "Branch $GITHUB_REF passed the illegal branch check"
  build:
    needs: skip-if-illegal-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag repository
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          default_bump: ${{ github.event.inputs.bump }}
          fetch_all_tags: true

      - name: Extract Docker metadata
        id: meta
        if: ${{ steps.tag.outputs.new_version != 'undefined' }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.tag.outputs.new_version }}

      - name: Build and push Docker image
        id: build-and-push
        if: ${{ steps.tag.outputs.new_version != 'undefined' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          file: nginx/Dockerfile
          build-args: ENVIRONMENT=prod

      - name: Print container version
        if: ${{ steps.tag.outputs.new_version != 'undefined' }}
        run: |
          echo "New container version: ${{ steps.tag.outputs.new_version }}"
          echo ':package: New container version: `${{ steps.tag.outputs.new_version }}`' >> $GITHUB_STEP_SUMMARY
