name: Protect

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: CI/CD
        run: |
          echo "Tests passing"
