on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fetch-pr-number:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.fetch-pr-number.pr-number }}
    steps:
      - name: Fetch PR Number
        id: fetch-pr-number
        run: |
          echo "Event Path: $GITHUB_EVENT_PATH"
          echo "Event Content:"
          cat $GITHUB_EVENT_PATH
          PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)
          echo "PR Number: $PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Bump
        id: bump
        run: |
          PULL_REQUEST_NUMBER=${{ steps.fetch-pr-number.pr_number }}
          echo "Fetching labels for pull request number: $PULL_REQUEST_NUMBER"
          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PULL_REQUEST_NUMBER}/labels")
          echo "Labels found: $LABELS"
          BUMP="minor"
          for label in $LABELS; do
            if [[ "$label" =~ ^(major|minor|patch)$ ]]; then
              BUMP="$label"
              break
            fi
          done
          echo "Selected bump version: $BUMP"
          echo "::set-output name=bump::$BUMP"
        

#  fetch-pr-labels:
#    needs: fetch-pr-number
#    uses: ./.github/workflows/version-bump.yaml
#    with:
#      pull_request_number: ${{ needs.fetch-pr-number.outputs.pr_number }}
