on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  fetch-pr-number:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Update image tag in stack_definition.yaml
      run: |
        IMAGE_VERSION=1.12
        sed -i "s|image:\s*name:\s*ghcr.io/world-wide-logistics/bulk-shipment-service/appruntime\s*tag:\s*.*|image:\n  name: ghcr.io/world-wide-logistics/bulk-shipment-service/appruntime\n  tag: ${IMAGE_VERSION}|" stack-definition.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add stack-definition.yaml
        git commit -m "Update image version in stack_definition.yaml"
        git push
      



#  fetch-pr-labels:
#    needs: fetch-pr-number
#    uses: ./.github/workflows/version-bump.yaml
#    with:
#      pull_request_number: ${{ needs.fetch-pr-number.outputs.pr_number }}
