name: Fetch PR Labels

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number

jobs:
  fetch-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "PR Number from input: ${{ inputs.pull_request_number }}"
      - name: Fetch labels from merged pull request
        id: fetch-labels
        run: |
          PULL_REQUEST_NUMBER=${{ inputs.pull_request_number }}
          echo "Fetching labels for pull request number: $PULL_REQUEST_NUMBER"
          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PULL_REQUEST_NUMBER}/labels")
          echo "Labels found: $LABELS"
          BUMP="minor"
          for label in $LABELS; do
            if [[ "$label" =~ ^(major|minor|patch)$ ]]; then
              BUMP="$label"
              break
            fi
          done
          echo "Selected bump version: $BUMP"
          echo "::set-output name=bump::$BUMP"
